stages:
  - build
  - release
  - deploy

build-prod: 
  stage: build
  image: docker:latest
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:prod .
  only:
    - master

build-staging:
  stage: build
  image: docker:latest
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:staging .
  only:
    - staging

release-prod:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  before_script:
    - docker login -u $CI_DEPLOY_USERNAME -p $CI_DEPLOY_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:prod
  only:
    - master
  cache: {}

release-staging:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  before_script:
    - docker login -u $CI_DEPLOY_USERNAME -p $CI_DEPLOY_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:staging
  only:
    - staging
  cache: {}

deploy-prod:
  stage: deploy
  before_script:
    - "which ssh-agent || (apk update && apk add openssh-client bash curl)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY_PROD\")"
    - export COMPOSE_HTTP_TIMEOUT=200
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml down --remove-orphans"
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml pull"
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml up -d"
  only:
    - prod

deploy-staging:
  stage: deploy
  before_script:
    - "which ssh-agent || (apk update && apk add openssh-client bash curl)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "$SSH_PRIVATE_KEY_STAGING"
    - bash -c "ssh-add <(echo $SSH_PRIVATE_KEY_STAGING)"
    - export COMPOSE_HTTP_TIMEOUT=200
    - ssh root@$HOST_STAGING "docker-compose -f ~/docker-compose.yml down --remove-orphans"
    - ssh root@$HOST_STAGING "docker-compose -f ~/docker-compose.yml pull"
    - ssh root@$HOST_STAGING "docker-compose -f ~/docker-compose.yml up -d"
  only:
    - staging





