stages:
  - build
  - release
  # - deploy

build-prod: 
  stage: build
  image: docker:latest
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:prod .
  only:
    - master

build-staging:
  stage: build
  image: docker:latest
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:staging .
  only:
    - staging

release-prod:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  before_script:
    - docker login -u $CI_DEPLOY_USERNAME -p $CI_DEPLOY_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:prod
  only:
    - master
  cache: {}

release-staging:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  before_script:
    - docker login -u $CI_DEPLOY_USERNAME -p $CI_DEPLOY_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:staging
  only:
    - staging
  cache: {}




