stages:
  - build
  - docker
  - docker-doc
  - deploy

#? BUILD STAGE

build-prod:
  stage: build
  image: node:16.13-alpine
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/
      - yarn.lock
  before_script:
    - yarn set version berry
  script:
    - yarn install --immutable
    - yarn run build --configuration production
    - yarn compodoc
  artifacts:
    paths:
      - dist/
      - documentation/
  only:
    - master

build-staging:
  stage: build
  image: node:16.13-alpine
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/
      - yarn.lock
  script:
    - yarn install --immutable
    - yarn run build --configuration staging
    - yarn compodoc
  artifacts:
    paths:
      - dist/
      - documentation/
  only:
    - staging

build-dev:
  stage: build
  image: node:16.13-alpine
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/
      - yarn.lock
  script:
    - yarn install --immutable
    - yarn run build --configuration staging
    - yarn compodoc
  artifacts:
    paths:
      - dist/
      - documentation/
  except:
    - staging
    - master

# ? DOCKER STAGE
docker-staging:
  stage: docker
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERTOKEN $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:staging .
    - docker push $CI_REGISTRY_IMAGE:staging
  dependencies:
    - build-staging
  only:
    - staging

docker-prod:
  stage: docker
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERTOKEN $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:prod .
    - docker push $CI_REGISTRY_IMAGE:prod
  dependencies:
    - build-prod
  only:
    - master

docker-dev:
  stage: docker
  image: docker:latest
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:prod .
  dependencies:
    - build-dev
  except:
    - staging
    - master


# ? DOCKER DOCUMENTATION STAGE

docker-doc-dev:
  stage: docker-doc
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERTOKEN $CI_REGISTRY
  script:
    - docker build -f Dockerfile.doc --tag $CI_DOC_IMAGE:dev .
    - docker push $CI_DOC_IMAGE:dev
  dependencies:
    - build-dev
  except:
    - master
    - staging

docker-doc-staging:
  stage: docker-doc
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERTOKEN $CI_REGISTRY
  script:
    - docker build -f Dockerfile.doc --tag $CI_DOC_IMAGE:staging .
    - docker push $CI_DOC_IMAGE:staging
  dependencies:
    - build-staging
  only:
    - staging

docker-doc-prod:
  stage: docker-doc
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_LOGIN -p $DOCKERTOKEN $CI_REGISTRY
  script:
    - docker build -f Dockerfile.doc --tag $CI_DOC_IMAGE:prod .
    - docker push $CI_DOC_IMAGE:prod
  dependencies:
    - build-prod
  only:
    - master


# ? DEPLOY STAGE
deploy-staging:
  stage: deploy
  before_script:
    - "which ssh-agent || (apk update && apk add openssh-client bash curl)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY_STAGING\")"
    - export COMPOSE_HTTP_TIMEOUT=200
    - ssh root@$HOST_STAGING "docker-compose -f ~/docker-compose.yml down --remove-orphans"
    - ssh root@$HOST_STAGING "docker-compose -f ~/docker-compose.yml pull"
    - ssh root@$HOST_STAGING "docker-compose -f ~/docker-compose.yml up -d"
  dependencies:
    - build-staging
  only:
    - staging

deploy-prod:
  stage: deploy
  before_script:
    - "which ssh-agent || (apk update && apk add openssh-client bash curl)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY_PROD\")"
    - export COMPOSE_HTTP_TIMEOUT=200
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml down --remove-orphans"
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml pull"
    - ssh root@$HOST_PROD "docker-compose -f ~/docker-compose.yml up -d"
  dependencies:
    - build-prod
  only:
    - master
